name: 'Reusable: GCP Authentication'

on:
  workflow_call:
    outputs:
      project_id:
        description: "GCP Project ID"
        value: ${{ jobs.authenticate.outputs.project_id }}

jobs:
  authenticate:
    name: 'Authenticate to GCP'
    runs-on: ubuntu-latest
    
    outputs:
      project_id: ${{ steps.setup.outputs.project_id }}
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: 'github-actions-deployer@dwhfinancial.iam.gserviceaccount.com'
      
      - name: 'Set up gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v2'
      
      - name: 'Setup project info'
        id: setup
        run: |
          echo "project_id=dwhfinancial" >> $GITHUB_OUTPUT
          gcloud config set project dwhfinancial